name: FENCE

on:
  pull_request:
    branches:
      - main

jobs:
  fence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Run FENCE on PR
        uses: ./
